spring:
  application:
    name: e-commerce

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # options: none, validate, update, create, create-drop
    show-sql: true

  jackson:
#    property-naming-strategy: SNAKE_CASE
    mapper:
      sort-properties-alphabetically: false

  sql:
    init:
      mode: always

server:
  port: 8080